# Generated by Django 5.2.4 on 2025-10-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('coach', 'Coach'), ('admin', 'Admin')], max_length=15),
        ),
    ]
