# Generated by Django 5.2.4 on 2025-11-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittly', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='document_link',
            field=models.URLField(blank=True),
        ),
    ]
