# Generated by Django 5.2.4 on 2025-11-08 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittly', '0004_project_document_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_doc_link', models.URLField(blank=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submitted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submittly.project')),
            ],
        ),
    ]
