# Generated by Django 5.2.4 on 2025-12-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittly', '0009_alter_attendance_date_alter_attendance_marked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.CharField(choices=[('exellent', 'Exellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending review', 'Pending Review'), ('reviewed', 'Reviewed')], max_length=15, null=True),
        ),
    ]
