# Generated by Django 5.2.4 on 2025-12-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittly', '0010_submission_feedback_submission_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='feedback',
        ),
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.CharField(blank=True, choices=[('exellent', 'Exellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(blank=True, choices=[('pending review', 'Pending Review'), ('reviewed', 'Reviewed')], max_length=15, null=True),
        ),
    ]
