# Generated by Django 5.2.4 on 2025-12-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittly', '0011_remove_submission_feedback_alter_submission_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(blank=True, choices=[('pending review', 'Pending Review'), ('reviewed', 'Reviewed')], default='pending review', max_length=15, null=True),
        ),
    ]
