# Generated by Django 5.2.4 on 2025-12-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittly', '0012_alter_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(blank=True, choices=[('pending review', 'Pending Review'), ('reviewed', 'Reviewed')], default='pending review', max_length=20, null=True),
        ),
    ]
