# Generated by Django 5.2.4 on 2025-12-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittly', '0013_alter_submission_grade_alter_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending review', 'Pending Review'), ('reviewed', 'Reviewed')], default='pending review', max_length=20),
        ),
    ]
