# Generated by Django 5.2.4 on 2025-12-17 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittly', '0014_alter_submission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('submission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submittly.submission')),
            ],
        ),
    ]
