# Generated by Django 6.0 on 2025-12-26 19:03

import submittly.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittly', '0015_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=submittly.models.getFilePath),
        ),
    ]
