# Generated by Django 6.0 on 2025-12-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittly', '0016_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=5, null=True),
        ),
    ]
